name: Sign document with Signum Container Agent (basic)

on:
  workflow_dispatch:
    inputs:
      signum_agent_image:
        description: "Container image to use (include tag)."
        required: false
        default: "repo.keyfactor.com/images/signum-agent:4.60.3"
      signum_agent_image_tar_gz:
        description: "Optional: URL (or repo-relative path) to a docker-archive .tar.gz created by `docker save | gzip`."
        required: false
        default: ""
  push:
    branches: ["main"]
    paths:
      - "filestosign/**"

permissions:
  contents: read

jobs:
  sign:
    runs-on: ubuntu-latest
    env:
      SIGNUM_REGISTRY: repo.keyfactor.com
      DEFAULT_SIGNUM_AGENT_IMAGE: repo.keyfactor.com/images/signum-agent:4.60.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Notes / Support Disclaimer
        shell: bash
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" <<'EOF'
          ## Signum Container Agent with Signing Tools – Support / Usage Notes
          Support issues: https://support.keyfactor.com/
          EOF

      - name: Configure Docker auth for repo.keyfactor.com (only needed if we pull)
        shell: bash
        env:
          JFROG_DOCKER_AUTH: ${{ secrets.JFROG_DOCKER_AUTH }}
        run: |
          set -euo pipefail
          if [[ -z "${JFROG_DOCKER_AUTH:-}" ]]; then
            echo "JFROG_DOCKER_AUTH not set; will still work if we load locally and never pull."
            exit 0
          fi

          mkdir -p ~/.docker
          cat > ~/.docker/config.json <<EOF
          {
            "auths": {
              "${SIGNUM_REGISTRY}": {
                "auth": "${JFROG_DOCKER_AUTH}"
              }
            }
          }
          EOF

          echo "== Docker auth configured for =="
          python3 - <<'PY'
          import json, os
          with open(os.path.expanduser("~/.docker/config.json")) as f:
              cfg=json.load(f)
          print(list(cfg.get("auths", {}).keys()))
          PY

      - name: Run Signum Agent container and list available certs (debug)
        shell: bash
        env:
          SIGNUM_HOSTNAME: ${{ secrets.SIGNUM_HOSTNAME }}
          SIGNUM_CLIENTID: ${{ secrets.SIGNUM_CLIENTID }}
          SIGNUM_USERNAME: ${{ secrets.SIGNUM_USERNAME }}
          SIGNUM_PASSWORD: ${{ secrets.SIGNUM_PASSWORD }}

          SIGNUM_AGENT_IMAGE: ${{ inputs.signum_agent_image || env.DEFAULT_SIGNUM_AGENT_IMAGE }}
          SIGNUM_AGENT_IMAGE_TAR_GZ: ${{ inputs.signum_agent_image_tar_gz }}
        run: |
          set -euo pipefail

          echo "== Basic checks =="
          echo "Runner: $(uname -a)"
          echo "Docker: $(docker --version)"
          echo "SIGNUM_HOSTNAME set? $([[ -n "${SIGNUM_HOSTNAME:-}" ]] && echo yes || echo no)"
          echo "SIGNUM_CLIENTID set? $([[ -n "${SIGNUM_CLIENTID:-}" ]] && echo yes || echo no)"
          echo "SIGNUM_USERNAME set? $([[ -n "${SIGNUM_USERNAME:-}" ]] && echo yes || echo no)"
          echo "SIGNUM_PASSWORD set? $([[ -n "${SIGNUM_PASSWORD:-}" ]] && echo yes || echo no)"

          echo "== Image ref we will use =="
          echo "${SIGNUM_AGENT_IMAGE}"

          echo "== Ensure there is something to sign =="
          mkdir -p filestosign
          if [ ! -f "filestosign/example-script.ps1" ]; then
            echo 'Write-Host "Hello from Signum signing demo"' > filestosign/example-script.ps1
          fi

          echo "== Attempt local import first (optional) =="
          if [[ -n "${SIGNUM_AGENT_IMAGE_TAR_GZ:-}" ]]; then
            echo "Tarball source provided: ${SIGNUM_AGENT_IMAGE_TAR_GZ}"
            TARBALL="signum-agent-image.tar.gz"

            if [[ "${SIGNUM_AGENT_IMAGE_TAR_GZ}" =~ ^https?:// ]]; then
              echo "Downloading tarball from URL..."
              curl -fsSL "${SIGNUM_AGENT_IMAGE_TAR_GZ}" -o "${TARBALL}"
            else
              echo "Using repo-relative tarball path..."
              [[ -f "${SIGNUM_AGENT_IMAGE_TAR_GZ}" ]] || { echo "ERROR: Not found: ${SIGNUM_AGENT_IMAGE_TAR_GZ}"; exit 1; }
              cp "${SIGNUM_AGENT_IMAGE_TAR_GZ}" "${TARBALL}"
            fi

            echo "Loading image into local Docker daemon..."
            gzip -dc "${TARBALL}" | docker load

            echo "Images after load:"
            docker image ls | sed -n '1,20p'

            if ! docker image inspect "${SIGNUM_AGENT_IMAGE}" >/dev/null 2>&1; then
              echo "Desired tag not present after load."
              echo "If your tarball contains a different tag, you must retag it to: ${SIGNUM_AGENT_IMAGE}"
              echo "Available tags for signum-agent after load:"
              docker image ls | grep -i signum || true
              exit 1
            fi
          else
            echo "No tarball provided; skipping docker load."
          fi

          echo "== Ensure image exists (pull only if needed) =="
          if docker image inspect "${SIGNUM_AGENT_IMAGE}" >/dev/null 2>&1; then
            echo "Using local image: ${SIGNUM_AGENT_IMAGE}"
          else
            echo "Local image not found. Pulling from registry..."
            docker pull "${SIGNUM_AGENT_IMAGE}"
          fi

          echo "== Run container =="
          docker run --name signum-agent -d \
            -v "$PWD/filestosign:/mnt/filestosign" \
            -e "SIGNUM_HOSTNAME=$SIGNUM_HOSTNAME" \
            -e "SIGNUM_CLIENTID=$SIGNUM_CLIENTID" \
            -e "SIGNUM_USERNAME=$SIGNUM_USERNAME" \
            -e "SIGNUM_PASSWORD=$SIGNUM_PASSWORD" \
            -e "SIGNUM_LOGLEVEL=HIGH" \
            -e "SIGNUM_LOGTYPE=FILE" \
            "${SIGNUM_AGENT_IMAGE}"

          echo "== Container status =="
          docker ps -a | sed -n '1,10p'

          echo "== List certs (signum-util lc) =="
          docker exec signum-agent signum-util lc | tee signum-certs.txt

          echo "### Signum cert listing (signum-util lc)" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          cat signum-certs.txt >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

      - name: Cleanup container
        if: always()
        shell: bash
        run: |
          docker rm -f signum-agent >/dev/null 2>&1 || true

      - name: Upload output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: signum-output
          path: |
            signum-certs.txt
            filestosign/example-script.ps1
