name: Sign document with Signum Container Agent (basic)

on:
  workflow_dispatch:
    inputs:
      signum_agent_image:
        description: "Container image to use (include tag)."
        required: false
        default: "repo.keyfactor.com/signum-cache/signum-agent:4.60.2"
  push:
    branches: ["main"]
    paths:
      - "filestosign/**"

permissions:
  contents: read

jobs:
  sign:
    runs-on: ubuntu-latest
    env:
      SIGNUM_REGISTRY: repo.keyfactor.com
      DEFAULT_SIGNUM_AGENT_IMAGE: repo.keyfactor.com/signum-cache/signum-agent:4.60.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Notes / Support Disclaimer
        shell: bash
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" <<'EOF'
          ## Signum Container Agent with Signing Tools – Support / Usage Notes
          Support issues: https://support.keyfactor.com/
          EOF

      - name: Docker login to repo.keyfactor.com (decode JFROG_DOCKER_AUTH)
        shell: bash
        env:
          JFROG_DOCKER_AUTH: ${{ secrets.JFROG_DOCKER_AUTH }}
        run: |
          set -euo pipefail

          if [[ -z "${JFROG_DOCKER_AUTH:-}" ]]; then
            echo "ERROR: secrets.JFROG_DOCKER_AUTH is empty/missing."
            exit 1
          fi

          # JFROG_DOCKER_AUTH is expected to be base64("username:password")
          CREDS="$(echo "${JFROG_DOCKER_AUTH}" | base64 -d || true)"
          if [[ -z "${CREDS}" || "${CREDS}" != *:* ]]; then
            echo "ERROR: secrets.JFROG_DOCKER_AUTH did not decode to 'username:password'."
            exit 1
          fi

          USERNAME="${CREDS%%:*}"
          PASSWORD="${CREDS#*:}"

          echo "${PASSWORD}" | docker login "${SIGNUM_REGISTRY}" -u "${USERNAME}" --password-stdin

          echo "== Registry /v2/ probe (helps distinguish auth vs missing repo) =="
          # 200 or 401/403 usually means registry reachable; 404 sometimes means wrong endpoint/proxy.
          curl -sS -o /dev/null -w "GET https://${SIGNUM_REGISTRY}/v2/ => HTTP %{http_code}\n" "https://${SIGNUM_REGISTRY}/v2/" || true

      - name: Run Signum Agent container and list available certs (debug)
        shell: bash
        env:
          SIGNUM_HOSTNAME: ${{ secrets.SIGNUM_HOSTNAME }}
          SIGNUM_CLIENTID: ${{ secrets.SIGNUM_CLIENTID }}
          SIGNUM_USERNAME: ${{ secrets.SIGNUM_USERNAME }}
          SIGNUM_PASSWORD: ${{ secrets.SIGNUM_PASSWORD }}
          SIGNUM_AGENT_IMAGE: ${{ inputs.signum_agent_image || env.DEFAULT_SIGNUM_AGENT_IMAGE }}
        run: |
          set -euo pipefail

          echo "== Basic checks =="
          echo "Runner: $(uname -a)"
          echo "Docker: $(docker --version)"
          echo "SIGNUM_HOSTNAME set? $([[ -n "${SIGNUM_HOSTNAME:-}" ]] && echo yes || echo no)"
          echo "SIGNUM_CLIENTID set? $([[ -n "${SIGNUM_CLIENTID:-}" ]] && echo yes || echo no)"
          echo "SIGNUM_USERNAME set? $([[ -n "${SIGNUM_USERNAME:-}" ]] && echo yes || echo no)"
          echo "SIGNUM_PASSWORD set? $([[ -n "${SIGNUM_PASSWORD:-}" ]] && echo yes || echo no)"

          echo "== Image ref we will use =="
          echo "${SIGNUM_AGENT_IMAGE}"

          echo "== Ensure there is something to sign =="
          mkdir -p filestosign
          if [ ! -f "filestosign/example-script.ps1" ]; then
            echo 'Write-Host "Hello from Signum signing demo"' > filestosign/example-script.ps1
          fi

          echo "== Pull Signum agent image =="
          # On GitHub-hosted runners it will never be local, so just pull.
          # If it fails, dump a bit of diagnostics.
          if ! docker pull "${SIGNUM_AGENT_IMAGE}"; then
            echo "ERROR: docker pull failed for ${SIGNUM_AGENT_IMAGE}"
            echo "== Diagnostics =="
            echo "Registry: ${SIGNUM_REGISTRY}"
            echo "Try confirming the repo/tag exists and that the registry endpoint is correct."
            echo "You can also try pulling a known-good image from the same registry/repo to validate auth."
            exit 1
          fi

          echo "== Run container =="
          docker run --name signum-agent -d \
            -v "$PWD/filestosign:/mnt/filestosign" \
            -e "SIGNUM_HOSTNAME=$SIGNUM_HOSTNAME" \
            -e "SIGNUM_CLIENTID=$SIGNUM_CLIENTID" \
            -e "SIGNUM_USERNAME=$SIGNUM_USERNAME" \
            -e "SIGNUM_PASSWORD=$SIGNUM_PASSWORD" \
            -e "SIGNUM_LOGLEVEL=HIGH" \
            -e "SIGNUM_LOGTYPE=FILE" \
            "${SIGNUM_AGENT_IMAGE}"

          echo "== Container status =="
          docker ps -a | sed -n '1,10p'

          echo "== List certs (signum-util lc) =="
          docker exec signum-agent signum-util lc | tee signum-certs.txt

          echo "### Signum cert listing (signum-util lc)" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          cat signum-certs.txt >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

      - name: Cleanup container
        if: always()
        shell: bash
        run: |
          docker rm -f signum-agent >/dev/null 2>&1 || true

      - name: Upload output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: signum-output
          path: |
            signum-certs.txt
            filestosign/example-script.ps1
